[package]
name = "try_opt"
version = "0.2.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
license = "MIT"
description = "[deprecated] Like try!, but for Option"
readme = "README.md"
repository = "https://github.com/crumblingstatue/try_opt"
keywords = ["early", "return", "try", "option"]
